parameters:
  - name: WorkingDirectory
    type: string

steps:
- script: |
    set -eo pipefail
    export UBSAN_OPTIONS="print_stacktrace=1"
    export ASAN_OPTIONS="alloc_dealloc_mismatch=0 symbolize=1 print_stacktrace=1"
    ninja check
  workingDirectory: ${{ parameters.WorkingDirectory }}
  displayName: Tests
